### PR TITLE
add doc for change_sensitive_fields

### PR DESCRIPTION
**Pull request by jhuangtw-dev**

### CODE REVIEW

**Comment by jhuangtw-dev** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6JkxKvGm&#x2F;4103-1-do-not-allow-a-user-sync-update-to-change-a-users-auth-identifier-or-email-address-unless-a-top-level-field-is-passed-change-s"> (1) Do not allow a user sync update to change a users auth identifier or email address unless a top-level field is passed &#39;change_sensitive_fields&#39; with value &#39;true&#39;</a>

**Comment by rjnordeen** [comment]
@jhuangtw-dev looks like this is updating the api docs, will this change behavior of the student syncs via CSV (see csv.rst)

**Comment by sgringwe** [comment]
@rjnordeen initially, no. this change will be api-only for now. if csv's run into issues we'll add support to the importer app as well, but it won't be a CSV file change probably.

**Comment by sgringwe** [comment]
@jhuangtw-dev looks good

**Pull request merged**
